name: Add a new technology radar item
description: Propose technology for addition to Babylon Technology Radar
title: "[RADAR UPDATE]: "
labels: ["tech-radar"]
assignees:
  - radar-admins
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: suggestor
    attributes:
      label: Suggestor
      description: Who is the owner?
      placeholder: ex. first.lastname@babylonhealth.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: description
      description: What is the technology?  Why is it needed at Babylon?   Any supporting documentation?
      placeholder: Please tell us more! 
    validations:
      required: true
  - type: dropdown
    id: ring
    attributes:
      label: Tech radar lifecycle
      options:
        - HOLD
        - ADOPT
        - ASSESS
        - TRIAL
    validations:
      required: true
  - type: dropdown
    id: quadrant
    attributes:
      label: Tech radar quadrant
      options:
        - Techniques
        - Platforms
        - Tools
        - Languages & Frameworks
    validations:
      required: true
